spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_economy?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
    open-in-view: false
  h2:
    console:
      enabled: false
  security:
    jwt:
      secret-key: ${JWT_SECRET:minha-chave-secreta-super-segura-para-desenvolvimento-local}
      expiration: 86400000 # 24 horas em milissegundos

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.myeconomy: DEBUG

# Configurações do Hikari (connection pool)
spring.datasource.hikari:
  maximum-pool-size: 5
  minimum-idle: 1
  idle-timeout: 300000
  connection-timeout: 20000
  max-lifetime: 1200000 